### ISSUE TITLE
"various forms of software and hardware implementations"

### ISSUE THREAD

**Issue by kurtseifried** [usnistgov/vulntology#17]
What about services? business processes? Is this supposed to strictly be limited to on premises hardware and software?

**Comment by Chris-Turner-NIST** [comment]
@kurtseifried  Thank you for the Question. Services in the cloud are in scope, but not sure how business processes would tie in currently. 

We are currently doing some cleanup of stale issues. I will be closing this issue.  If you would like to open a new issue that provides more detail on how these topics fit withing the Vulntology use case in addition to a proposed method of integrating it into the current data model please do not hesitate to do so. 

Additionally, the Vulntology has refined quite a bit since your comment (albeit in nuanced ways) and you may want to take another look.
