### ISSUE TITLE
Add additional references to physical impact classification

### ISSUE THREAD

**Issue by santosomar** [usnistgov/vulntology#21]
The existing specification value for [physical impact](https://github.com/usnistgov/vulntology/blob/master/specification/values/physical-impact.md) includes a reference to ISO/IEC 14971:2007 under "Human Injury".  

This issue is to track and add other references to impact classifications  that exists in the industry (i.e., FDA has [adverse event codes](https://www.fda.gov/medical-devices/mandatory-reporting-requirements-manufacturers-importers-and-device-user-facilities/mdr-adverse-event-codes), etc.).

**Comment by david-waltermire-nist** [comment]
@santosomar Do you have specific references in mind that you would like to have added, or are you asking for more research to be done?

**Comment by santosomar** [comment]
I think both ;-) FDA has the "adverse event codes"; however, perhaps a bit more research could be done, as well. I filed this issue when we were talking back in March in DC.

**Comment by Chris-Turner-NIST** [comment]
@santosomar thank you for the request. At this time we are only going to be moving forward on issues that provide a clear advisement including details on how the data type addition meets the need within the Vulntology use case and exactly how it would be integrated. As it currently stands this issue is a bit too generic to be actionable. 

I will be closing the issue, but if you would like to open another with the requested detail above please do not hesitate to do so. Additionally, the Vulntology has refined quite a bit since your comment (albeit in nuanced ways) and you may want to take another look.

**Comment by santosomar** [comment]
Absolutely! That was from 4 years ago and I assume that a lot has changed since then ;-)
